/**
 * @file    src/lib/midtrans.ts
 * @brief   Service layer client executing HTTPS requests to Midtrans Core API charging endpoints
 * @author  ray
 * @created 2026-08-07
 * @todo    - Support query endpoint check status for suspicious webhook validation fallbacks
 */

import { MidtransQRISResponse } from "@/types/donation";

const isProduction = process.env.MIDTRANS_IS_PRODUCTION === "true";
const MIDTRANS_API_BASE = isProduction
  ? "https://api.midtrans.com"
  : "https://api.sandbox.midtrans.com";

/**
 * Retrieve Midtrans Basic Authentication base64 token dynamically
 */
function getBasicAuthToken(): string {
  const key = process.env.MIDTRANS_SERVER_KEY;
  if (!key) {
    throw new Error("Missing MIDTRANS_SERVER_KEY server configuration.");
  }
  return Buffer.from(`${key}:`).toString("base64");
}

/**
 * Execute a QRIS charge transaction request to Midtrans API
 * @param orderId Unique order reference generated by server
 * @param amount Donation amount in IDR integer format
 */
export async function chargeQRIS(orderId: string, amount: number): Promise<MidtransQRISResponse> {
  const payload = {
    payment_type: "qris",
    transaction_details: {
      order_id: orderId,
      gross_amount: amount,
    },
    qris: {
      acquirer: "gopay",
    },
  };

  const basicAuthToken = getBasicAuthToken();

  const response = await fetch(`${MIDTRANS_API_BASE}/v2/charge`, {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      Authorization: `Basic ${basicAuthToken}`,
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Midtrans API charge failed with status ${response.status}: ${errorBody}`);
  }

  const data = await response.json();
  return data as MidtransQRISResponse;
}

/**
 * Retrieve transaction status details directly from Midtrans status endpoint
 * @param orderId Unique order identifier
 */
export async function getTransactionStatus(orderId: string) {
  const basicAuthToken = getBasicAuthToken();

  const response = await fetch(`${MIDTRANS_API_BASE}/v2/${orderId}/status`, {
    method: "GET",
    headers: {
      Accept: "application/json",
      Authorization: `Basic ${basicAuthToken}`,
    },
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Midtrans API getStatus failed with status ${response.status}: ${errorBody}`);
  }

  return response.json();
}
